# Generated by Django 4.2.6 on 2023-11-08 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recognizerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(max_length=40)),
                ('user', models.CharField(max_length=100)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recognizerapp.images')),
            ],
        ),
    ]
